MusicLibraryTest2/Controllers/AdminPagesController.cs
using MusicLibraryTest2.Models;
using MySqlConnector;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web.Mvc;
using NAudio.Wave;
using System.Web.Profile;
using MusicLibraryTest2.Data;
using Microsoft.Ajax.Utilities;
using NAudio.CoreAudioApi;

namespace MusicLibraryTest2.Controllers
{
    public class AdminPagesController : Controller
    {
        string connection = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
        MusicDatabase db = new MusicDatabase();

        public ActionResult AdminPage()
        {
            ProfileModel profileModel = (ProfileModel)Session["ProfileInfo"];

            return View("AdminPage", profileModel);
        }
        public ActionResult UserList()
        {
            List<User> users = new List<User>();
            string sortBy;
            bool isAscending;
            DateTime? fromDate;
            DateTime? toDate;
            string role;
            bool noArchived;

            if (!string.IsNullOrEmpty(Request.QueryString["fromDate"]))
            {
                fromDate = DateTime.Parse(Request.QueryString["fromDate"]);
            }
            else fromDate = null;

            if (!string.IsNullOrEmpty(Request.QueryString["toDate"]))
            {
                toDate = DateTime.Parse(Request.QueryString["toDate"]);
            }
            else toDate = null;

            if (fromDate != null && toDate != null)
            {
                users = db.GetUsersData(fromDate.Value, toDate.Value);
            }
            else
            {
                users = db.GetUsersData();
            }

            if (!string.IsNullOrEmpty(Request.QueryString["role"]))
            {
                role = Request.QueryString["role"];
                users = users.Where(u => u.Role == role).ToList();
            }
            else role = "";
            
            if (!string.IsNullOrEmpty(Request.QueryString["noArchived"]))
            {
                noArchived = bool.Parse(Request.QueryString["noArchived"]);
                if (noArchived)
                users = users.Where(u => u.IsArchived != noArchived).ToList();
            }
            else noArchived = false;

            if (!string.IsNullOrEmpty(Request.QueryString["sortBy"]))
            {
                sortBy = Request.QueryString["sortBy"];
            }
            else sortBy = "id";

            if (!string.IsNullOrEmpty(Request.QueryString["isAscending"]))
            {
                isAscending = bool.Parse(Request.QueryString["isAscending"]);
            }
            else isAscending = true;

            switch (sortBy)
            {
                case "id":
                    if (isAscending)
                        users = users.OrderBy(u => u.Id).ToList();
                    else
                        users = users.OrderByDescending(u => u.Id).ToList();
                    break;
                case "name":
                    if (isAscending)
                        users = users.OrderBy(u => u.Username).ToList();
                    else
                        users = users.OrderByDescending(u => u.Username).ToList();
                    break;
                case "created":
                    if (isAscending)
                        users = users.OrderBy(u => u.CreatedAt).ToList();
                    else
                        users = users.OrderByDescending(u => u.CreatedAt).ToList();
                    break;
                case "login":
                    if (isAscending)
                        users = users.OrderBy(u => u.LastLoginAt).ToList();
                    else
                        users = users.OrderByDescending(u => u.LastLoginAt).ToList();
                    break;
                case "archived":
                    if (isAscending)
                        users = users.OrderBy(u => u.IsArchived).ToList();
                    else
                        users = users.OrderByDescending(u => u.IsArchived).ToList();
                    break;
                default:
                    users = users.OrderBy(u => u.Id).ToList();
                    break;
            }
            ViewBag.userCount = users.DistinctBy(u => u.Id).Count();
            ViewBag.sortBy = sortBy;
            ViewBag.isAscending = isAscending;
            ViewBag.fromDate = fromDate;
            ViewBag.toDate = toDate;
            ViewBag.role = role;
            ViewBag.noArchived = noArchived;

            return PartialView(users);
        }

        public ActionResult SongList()
        {
            List<Song> songs = new List<Song>();
            string sortBy;
            bool isAscending;
            DateTime? fromDate;
            DateTime? toDate;
            string genre;
            bool noArchived;

            if (!string.IsNullOrEmpty(Request.QueryString["fromDate"]))
            {
                fromDate = DateTime.Parse(Request.QueryString["fromDate"]);
            }
            else fromDate = null;

            if (!string.IsNullOrEmpty(Request.QueryString["toDate"]))
            {
                toDate = DateTime.Parse(Request.QueryString["toDate"]);
            }
            else toDate = null;

            if (fromDate != null && toDate != null)
            {
                songs = db.GetSongData(fromDate.Value, toDate.Value);
            }
            else
            {
                songs = db.GetSongData();
            }

            if (!string.IsNullOrEmpty(Request.QueryString["genre"]))
            {
                genre = Request.QueryString["genre"];
                songs = songs.Where(s => s.Genre.ToLower() == genre).ToList();
            }
            else genre = "";

            if (!string.IsNullOrEmpty(Request.QueryString["noArchived"]))
            {
                noArchived = bool.Parse(Request.QueryString["noArchived"]);
                if (noArchived)
                    songs = songs.Where(s => s.IsArchived != noArchived).ToList();
            }
            else noArchived = false;

            if (!string.IsNullOrEmpty(Request.QueryString["sortBy"]))
            {
                sortBy = Request.QueryString["sortBy"];
            }
            else sortBy = "created";

            if (!string.IsNullOrEmpty(Request.QueryString["isAscending"]))
            {
                isAscending = bool.Parse(Request.QueryString["isAscending"]);
            }
            else isAscending = true;

            switch (sortBy)
            {
                case "title":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.Title).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.Title).ToList();
                    break;
                case "genre":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.Genre).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.Genre).ToList();
                    break;
                case "view":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.Views).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.Views).ToList();
                    break;
                case "like":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.Likes).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.Likes).ToList();
                    break;
                case "artist":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.Artist).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.Artist).ToList();
                    break;
                case "album":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.AlbumName).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.AlbumName).ToList();
                    break;
                case "created":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.CreatedAt).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.CreatedAt).ToList();
                    break;
                case "archived":
                    if (isAscending)
                        songs = songs.OrderBy(s => s.IsArchived).ToList();
                    else
                        songs = songs.OrderByDescending(s => s.IsArchived).ToList();
                    break;
                default:
                    songs = songs.OrderBy(s => s.CreatedAt).ToList();
                    break;
            }
            ViewBag.songCount = songs.DistinctBy(s => s.Id).Count();
            ViewBag.sortBy = sortBy;
            ViewBag.isAscending = isAscending;
            ViewBag.fromDate = fromDate;
            ViewBag.toDate = toDate;
            ViewBag.genre = genre;
            ViewBag.noArchived = noArchived;

            return PartialView(songs);
        }

        public ActionResult BrowseAllSongs()
        {
            List<SongModel> songList = new List<SongModel>();

            using (MySqlConnection con = new MySqlConnection(connection))
            {
                MySqlCommand cmd = new MySqlCommand($"SELECT song.Id, song.title, song.genre, song.likes, song.views" +
                    $" FROM song WHERE song.isArchived = 0 ORDER BY views DESC LIMIT 50", con);

                cmd.CommandType = System.Data.CommandType.Text;
                con.Open();

                MySqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    var songModel = new SongModel

MusicLibraryTest2/Views/AdminPages/AdminPage.cshtml
@model MusicLibraryTest2.Models.ProfileModel
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<head>
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>

@Html.Action("ShowNavbar", "Home")
<br />
<br />

<body>
    <div class="mainBox">

        <span class="get-users toggle-button">
            <span class="triangle"></span>
            Manage Users
        </span>

        <span style="margin: 0 10px;">|</span>
        @Html.ActionLink("User List", "UserList", new { sortBy = "id", isAscending = true })
        <span style="margin: 0 10px;">|</span>
        @Html.ActionLink("Song List", "SongList", new { sortBy = "created", isAscending = false })

        <div class="songs toggle-container sub-container" id="manage-container"></div>

        <img style="width: 100%; height: 100%;" src="~/Content/guitar-756326_1920.jpg" />

    </div>
</body>


<script>
    $(document).ready(function () {

        $('.get-users').click(function () {

            var loaded = false;
            var $manageContainer = $('#manage-container')

            if (!loaded) {
                $.ajax({
                data: null,
                url: '/AdminPages/GetUsers',
                    success: function(data) {
                        $manageContainer.html(data);
                        loaded = true;
                    }
                });
            }
            $(this).find('.triangle').toggleClass('rotate');
            $manageContainer.toggle();
        });
    });
</script>

MusicLibraryTest2/Views/AdminPages/SongList.cshtml
@model IEnumerable<MusicLibraryTest2.Models.Song>

@{
    Layout = null;
    string sortBy = "id";
    bool isAscending = true;
    DateTime fromDate;
    DateTime toDate;
}
<h1>Song Count: @ViewBag.songCount</h1>
<h2>Sorting Variables:</h2>
<ul>
    <li>Sort By: @ViewBag.sortBy</li>
    <li>Sort Order: @(ViewBag.isAscending ? "Ascending" : "Descending")</li>
    @if (ViewBag.fromDate != null && ViewBag.toDate != null)
    {
        <li>Date Range: @ViewBag.fromDate.ToShortDateString() - @ViewBag.toDate.ToShortDateString()</li>
    }
    <li>Hide Archived: @ViewBag.noArchived</li>
</ul>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserList</title>
</head>
<body style="background-color: #7d2935">
    <div style="background-color: #CCCCCC; width: 80%; display: block; align-content: center; border-radius: 1rem; margin: 2rem; padding: 2rem">
        <p>
            @Html.ActionLink("Back", "AdminPage")
            <br /><br />
            @Html.ActionLink("Sort By Title", "SongList", new { sortBy = "title", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Genre", "SongList", new { sortBy = "genre", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By View", "SongList", new { sortBy = "view", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Like", "SongList", new { sortBy = "like", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Artist", "SongList", new { sortBy = "artist", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Album", "SongList", new { sortBy = "album", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Created Date", "SongList", new { sortBy = "created", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Archived", "SongList", new { sortBy = "archived", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            <br /><br />
            @Html.ActionLink("Ascending", "SongList", new { ViewBag.sortBy, isAscending = true, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Descending", "SongList", new { ViewBag.sortBy, isAscending = false, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
        </p>
        <p></p>
        <form method="get" action="@Url.Action("SongList", "AdminPages", new { sortBy = ViewBag.sortBy, isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, genre = ViewBag.genre, noArchived = ViewBag.noArchived  })">
            <label for="genreFilter">Genre:</label>
            <select id="genreFilter" name="genre">
                <option value="">All</option>
                <option value="pop">Pop</option>
                <option value="rock">Rock</option>
                <option value="metal">Metal</option>
                <option value="blues">Blues</option>
                <option value="folk">Folk</option>
                <option value="classical">Classical</option>
                <option value="electronic">Electronic</option>
                <option value="hip hop">Hip Hop</option>
                <option value="jazz">Jazz</option>
                <option value="rap">Rap</option>
                <option value="techno">Techno</option>
            </select>
            <input type="checkbox" id="noArchived" name="noArchived" value="true">
            <label for="noArchived">Hide Archived</label>
            <div>
                <label for="fromDate">From Date:</label>
                <input type="date" id="fromDate" name="fromDate">

                <label for="toDate">To Date:</label>
                <input type="date" id="toDate" name="toDate">
            </div>
            <input type="submit" value="Search">
        </form>
        <style>
            table {
                border-collapse: collapse;
                width: 100%;
            }

            th, td {
                padding: 8px;
                text-align: left;
                border-bottom: 1px solid #ddd;
            }

            th {
                background-color: #f2f2f2;
            }
        </style>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Genre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Views)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Likes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Artist)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AlbumName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsArchived)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Genre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Views)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Likes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Artist)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlbumName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsArchived)
                    </td>
                </tr>
            }

        </table>
    </div>
</body>
</html>

MusicLibraryTest2/Views/AdminPages/UserList.cshtml
@model IEnumerable<MusicLibraryTest2.Models.User>

@{
    Layout = null;
    //string sortBy = "id";
    //bool isAscending = true;
    //DateTime fromDate;
    //DateTime toDate;
}

<h1>User Count: @ViewBag.userCount</h1>
<h2>Sorting Variables:</h2>
<ul>
    <li>Sort By: @ViewBag.sortBy</li>
    <li>Sort Order: @(ViewBag.isAscending ? "Ascending" : "Descending")</li>
    @if (ViewBag.fromDate != null && ViewBag.toDate != null)
    {
        <li>Date Range: @ViewBag.fromDate.ToShortDateString() - @ViewBag.toDate.ToShortDateString()</li>
    }
    <li>Role: @ViewBag.role</li>
    <li>Hide Archived: @ViewBag.noArchived</li>
</ul>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserList</title>
</head>
<body style="background-color: #7d2935">
    <div style="background-color: #CCCCCC; width: 80%; display: block; align-content: center; border-radius: 1rem; margin: 2rem; padding: 2rem">
        <p>
            @Html.ActionLink("Back", "AdminPage")
            <br /><br />
            @Html.ActionLink("Sort By ID", "UserList", new { sortBy = "id", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Name", "UserList", new { sortBy = "name", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Created Date", "UserList", new { sortBy = "created", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Login Time", "UserList", new { sortBy = "login", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Sort By Archived", "UserList", new { sortBy = "archived", isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            <br /><br />
            @Html.ActionLink("Ascending", "UserList", new { ViewBag.sortBy, isAscending = true, ViewBag.fromDate, ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
            @Html.ActionLink("Descending", "UserList", new { ViewBag.sortBy, isAscending = false, ViewBag.fromDate, ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })
            <span style="margin: 0 10px;">|</span>
        </p>
        <p></p>
        <form method="get" action="@Url.Action("UserList", "AdminPages", new { sortBy = ViewBag.sortBy, isAscending = ViewBag.isAscending, fromDate = ViewBag.fromDate, toDate = ViewBag.toDate, role = ViewBag.role, noArchived = ViewBag.noArchived })">

                <label for="roleFilter">Role:</label>
                <select id="roleFilter" name="role">
                    <option value="">All</option>
                    <option value="user">User</option>
                    <option value="admin">Admin</option>
                    <option value="artist">Artist</option>
                </select>
                <input type="checkbox" id="noArchived" name="noArchived" value="true">
                <label for="noArchived">Hide Archived</label>
            <div>
                <label for="fromDate">From Date:</label>
                <input type="date" id="fromDate" name="fromDate">

                <label for="toDate">To Date:</label>
                <input type="date" id="toDate" name="toDate">
            </div>

            <input type="submit" value="Search">
        </form>


        <style>
            table {
                border-collapse: collapse;
                width: 100%;
            }

            th, td {
                padding: 8px;
                text-align: left;
                border-bottom: 1px solid #ddd;
            }

            th {
                background-color: #f2f2f2;
            }
        </style>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Username)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Role)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModifiedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastLoginAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsArchived)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Role)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastLoginAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsArchived)
                    </td>
                </tr>
            }

        </table>
    </div>
</body>
</html>

MusicLibraryTest2/Views/AdminPages/_CreateUserForm.cshtml
@model MusicLibraryTest2.Models.UserModel

<div class="entry-box">
    @using (Html.BeginForm("CreateUser", "AdminPages", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.LabelFor(model => model.Username)
        <br>
        @Html.TextBoxFor(model => model.Username)
        <br>
        @Html.CheckBoxFor(model => model.isArtist)
        <br>
        @Html.CheckBoxFor(model => model.isAdmin)
        <br>

        <input id="Submit" type="submit" value="Create" />
    }
</div>

MusicLibraryTest2/Views/AdminPages/_UserDeleteList.cshtml
@model MusicLibraryTest2.Models.UserModels

@foreach (var user in Model.UserList)
 {
<div class="songBox" id="userBox-@user.Id">

    <span class="report-head">Account Name: </span>
    <span class="report-body">@user.Username</span>
    <br />
    <br />
    @if (user.isArtist)
    {
        <span class="report-head">Role: </span>
        <span class="report-body"> Artist</span>
    }
    else
    {
        <span class="report-head">Add Artist Role </span>
        <button class="add-artist-button" data-archive-user-id="@user.Id">
            <i class="fa-regular fa-square-plus"></i>
        </button>
    }
    <br />
    <br />

    @if (user.isAdmin)
    {
        <span class="report-head">Role: </span>
        <span class="report-body"> Admin</span>
    }
    else
    {
        <span class="report-head">Add Admin Role </span>
        <button class="add-admin-button" data-archive-user-id="@user.Id">
            <i class="fa-regular fa-square-plus"></i>
        </button>
    }
    <br />
    <br />

    <button class="archive-button" data-archive-user-id="@user.Id">
        <i class="fa-solid fa-square-xmark unclicked-icon"></i>
    </button>
</div>
 }

@if (Model.UserList.Count == 0)
 {
    <div class="has-error">No User to Display</div>
 }

<script src="https://kit.fontawesome.com/0baa800b55.js" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {

        $('.add-admin-button').click(function () {
            var button = $(this);
            var userArchiveId = $(this).data('archive-user-id');

                $.ajax({
                    url: '/AdminPages/MakeUserAdmin',
                    type: 'POST',
                    data: { userId: userArchiveId },
                    success: function (data) {
                        button.addClass('add-button-glow');

                        setTimeout(function () {
                            button.addClass('add-button-glow');
                        }, 500);

                        button.addClass('add-button-fade');

                        setTimeout(function () {
                            button.addClass('add-button-fade');
                        }, 500);

                        button.toggle();
                    }
                });
        });

        $('.add-artist-button').click(function () {
            var button = $(this);
            var userArchiveId = $(this).data('archive-user-id');

                $.ajax({
                    url: '/AdminPages/MakeUserArtist',
                    type: 'POST',
                    data: { userId: userArchiveId },
                    success: function (data) {
                        button.addClass('add-button-glow');

                        setTimeout(function () {
                            button.addClass('add-button-glow');
                        }, 500);

                        button.addClass('add-button-fade');

                        setTimeout(function () {
                            button.addClass('add-button-fade');
                        }, 500);

                        button.toggle();
                    }
                });
        });

        $('.archive-button').click(function () {

            var button = $(this);
            var userArchiveId = $(this).data('archive-user-id');
            var $userBox = $('#userBox-' + userArchiveId);
                 $.ajax({
                     url: '/AdminPages/ArchiveUser',
                     type: 'GET',
                     data: { userId: userArchiveId },
                     success: function (data) {

                         button.find('.unclicked-icon').removeClass('unclicked-icon');
                         setTimeout(function () {
                             button.find('.unclicked-icon').removeClass('unclicked-icon');
                         }, 1000);
                         $userBox.toggle();
                     }
                 });
        });

    });
</script>