MusicLibraryTest2/Controllers/ArtistPagesController.cs
using MusicLibraryTest2.Models;
using MySqlConnector;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Web.Mvc;
using NAudio.Wave;
using System.Web.Profile;


namespace MusicLibraryTest2.Controllers
{
    public class ArtistPagesController : Controller
    {
        string connection = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
        public ActionResult GetArtist(int? artistId)
        {
            using (MySqlConnection con = new MySqlConnection(connection))
            {
                MySqlCommand cmd = new MySqlCommand($"SELECT * FROM artist WHERE artist.Id = {artistId}", con);
                cmd.CommandType = System.Data.CommandType.Text;
                con.Open();

                var artistModel = new ArtistModel();

                MySqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    artistModel.Id = Convert.ToInt32(reader["Id"]);
                    artistModel.AlbumId = Convert.ToInt32(reader["albumId"]);
                    artistModel.Name = reader["name"].ToString();
                    artistModel.IsArchived = Convert.ToBoolean(reader["isArchived"]);
                }
                return View(artistModel);
            }
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ArtistPage()
        {
            ProfileModel profileModel = (ProfileModel)Session["ProfileInfo"];

            return View("ArtistPage", profileModel);
        }

        public ActionResult AddMusic()
        {
            ProfileModel profileModel = (ProfileModel)Session["ProfileInfo"];

            return PartialView("_AddMusic", profileModel);
        }

        public ActionResult CreateSongForm()
        {
            CreateSongModel createSongModel = new CreateSongModel();

            ProfileModel profileModel = (ProfileModel)Session["ProfileInfo"];

            createSongModel.ProfileId = profileModel.Id;

            createSongModel.UserAlbumDictionary = GetDictionaryOfUserAlbums(profileModel.Id);

            return PartialView("_CreateSongForm", createSongModel);
        }

        public ActionResult CreateAlbumForm(CreateAlbumModel createAlbumModel)
        {
            return PartialView("_CreateAlbumForm", createAlbumModel);
        }

        public ActionResult EditAlbumForm(AlbumModel albumModel)
        {
            EditAlbumModel editAlbumModel = new EditAlbumModel()
            {
                Id = albumModel.Id,
                Title = albumModel.Title,
                Genre = albumModel.Genre,
                Description = albumModel.Description,
            };

            return PartialView("_EditAlbumForm", editAlbumModel);
        }

        public ActionResult EditSongForm(SongModel songModel)
        {
            EditSongModel editSongModel = new EditSongModel()
            {
                Id = songModel.Id,
                Title = songModel.Title,
                Genre = songModel.Genre,
            };

            return PartialView("_EditSongForm", editSongModel);
        }

        [HttpPost]
        public ActionResult EditAlbum(EditAlbumModel editAlbumModel)
        {
            ProfileModel profile = (ProfileModel)Session["ProfileInfo"];

            using (MySqlConnection con = new MySqlConnection(connection))
            {
                string command = $"UPDATE album SET title = '{editAlbumModel.Title}', description = '{editAlbumModel.Description}', genre = '{editAlbumModel.Genre}'"+
                    $"WHERE Id = {editAlbumModel.Id}";

                MySqlCommand cmd = new MySqlCommand(command, con);
                cmd.CommandType = System.Data.CommandType.Text;
                con.Open();
                if (cmd.ExecuteNonQuery() > 0)
                {

                }
            }
            return View("ArtistPage", (ProfileModel)Session["ProfileInfo"]);
        }

        [HttpPost]
        public ActionResult EditSong(EditSongModel editSongModel)
        {
            ProfileModel profile = (ProfileModel)Session["ProfileInfo"];

            using (MySqlConnection con = new MySqlConnection(connection))
            {
                string command = $"UPDATE song SET title = '{editSongModel.Title}', genre = '{editSongModel.Genre}'" +
                    $"WHERE Id = {editSongModel.Id}";

                MySqlCommand cmd = new MySqlCommand(command, con);
                cmd.CommandType = System.Data.CommandType.Text;
                con.Open();
                if (cmd.ExecuteNonQuery() > 0)
                {

                }
            }
            return View("ArtistPage", (ProfileModel)Session["ProfileInfo"]);
        }

        [HttpPost]
        public ActionResult CreateSong(CreateSongModel createSongModel)
        {

            ProfileModel profile = (ProfileModel)Session["ProfileInfo"];

            MemoryStream target = new MemoryStream();
            createSongModel.songFile.InputStream.CopyTo(target);
            byte[] songData = target.ToArray();

            using (MySqlConnection con = new MySqlConnection(connection))
            {
                MySqlCommand cmd = new MySqlCommand($"INSERT INTO song (title,genre,songFile) values ('{createSongModel.Title}','{createSongModel.Genre}',@data)", con);
                cmd.Parameters.Add("@data", MySqlDbType.Blob).Value = songData;
                cmd.CommandType = System.Data.CommandType.Text;
                con.Open();
                if (cmd.ExecuteNonQuery() > 0)
                {

                }
            }
            if (createSongModel.albumId != 0)
            {
                //create user_album relationship
                using (MySqlConnection con = new MySqlConnection(connection))
                {
                    string command = $"INSERT INTO album_songs (albumId,songId) values" +
                        $" ({createSongModel.albumId}, (SELECT song.id from song WHERE song.title = '{createSongModel.Title}' AND song.genre = '{createSongModel.Genre}'))";

                    MySqlCommand cmd = new MySqlCommand(command, con);
                    cmd.Parameters.Add("@data", MySqlDbType.Blob).Value = songData;
                    cmd.CommandType = System.Data.CommandType.Text;
                    con.Open();
                    if (cmd.ExecuteNonQuery() > 0)
                    {

                    }
                }
            }
            else
            {
                //create user_song relationship
                using (MySqlConnection con = new MySqlConnection(connection))
                {
                    string command = $"INSERT INTO user_songs (userId,songId, songTitle) values" +
                        $" ({profile.Id}, (SELECT id FROM song WHERE title = '{createSongModel.Title}' AND genre = '{createSongModel.Genre}' LIMIT 1)," +
                        $"(SELECT title FROM song WHERE title = '{createSongModel.Title}' AND genre = '{createSongModel.Genre}' LIMIT 1))";

                    MySqlCommand cmd = new MySqlCommand(command, con);
                    cmd.Parameters.Add("@data", MySqlDbType.Blob).Value = songData;
                    cmd.CommandType = System.Data.CommandType.Text;
                    con.Open();
                    if (cmd.ExecuteNonQuery() > 0)
                    {

                    }
                }

            }

            return View("ArtistPage", (ProfileModel)Session["ProfileInfo"]);
        }

        public ActionResult GetArtistReport()
        {
            ProfileModel profile = (ProfileModel)Session["ProfileInfo"];

            List<ArtistReportModel> artistReports = new List<ArtistReportModel>();

            using (MySqlConnection con = new MySqlConnection(connection))
            {

                string command = $"SELECT * FROM" +

                                " (SELECT * FROM" +
                                  
                                " (SELECT song.title as song_title1, album.title as album_title1," +
                                " song.genre as genre1, COUNT(*) as MonthlyLikes" +
                                " FROM album, album_songs, song, user_likes, user_albums" +
                                " WHERE album.id = album_songs.albumid" +
                                " AND album_songs.songId = song.id" +
                                " AND user_likes.created_at > now() - interval 1 month" +
                                " AND user_likes.songId = song.id" +
                                " AND album.id = user_albums.albumId" +
                                " AND song.isArchived = 0" +
                                $" AND user_albums.userid = {profile.Id}" +
                                " GROUP BY song_title1, album_title1, genre1" +
                                " ORDER BY MonthlyLikes desc) res1" +
                                  
                                " INNER JOIN" +
                                  
                                " (SELECT song.title as song_title2, album.title as album_title2," +
                                " song.genre as genre2, COUNT(*) as MonthlyViews" +
                                " FROM album, album_songs, song, user_views, user_albums" +
                                " WHERE album.id = album_songs.albumid" +
                                " AND album_songs.songId = song.id" +
                                " AND user_views.time_viewed > now() - interval 1 month" +
                                " AND user_views.songId = song.id" +
                                " AND album.id = user_albums.albumId" +
                                " AND song.isArchived = 0" +
                                $" AND user_albums.userid = {profile.Id}" +

MusicLibraryTest2/Views/ArtistPages/ArtistPage.cshtml
@model MusicLibraryTest2.Models.ProfileModel
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<head>
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>

@Html.Action("ShowNavbar", "Home")

<body>
    <div class="mainBox">

        <span class="get-add-music toggle-button">
            <span class="triangle"></span>
            Add Music
        </span>

        <span class="get-albums toggle-button">
            <span class="triangle"></span>
            Albums
        </span>

        <span class="get-milestones toggle-button">
            <span class="triangle"></span>
            Milestones
        </span>

        <span class="get-artist-report toggle-button">
            <span class="triangle"></span>
            Artist Report
        </span>

        <div class="addMusic toggle-container" id="add-music-container"></div>
        <div class="albums toggle-container" id="albums-container"></div>
        <div class="milestones toggle-container" id="get-milestones-container"></div>
        <div class="aritst-report toggle-container" id="get-artist-report-container"></div>

        <img style="width: 100%; height: 100%;" src="~/Content/music-free-micinterface.jpg" />

    </div>
</body>

<script src="https://kit.fontawesome.com/0baa800b55.js" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {

        var addMusicLoaded = false;
        var albumsLoaded = false;

        $('.get-add-music').click(function () {

            var $addMusicContainer = $('#add-music-container')

            if (!addMusicLoaded) {
                $.ajax({
                data: null,
                url: '/ArtistPages/AddMusic',
                    success: function(data) {
                        $addMusicContainer.html(data);
                        addMusicLoaded = true;
                    }
                });
            }
            $(this).find('.triangle').toggleClass('rotate');
            $addMusicContainer.toggle();
        });
        $('.get-albums').click(function () {

            var $albumsContainer = $('#albums-container')

            if (!albumsLoaded) {
                $.ajax({
                url: '/ArtistPages/GetUserAlbums',
                data: { userId: '@Model.Id' },
                    success: function(data) {
                        $albumsContainer.html(data);
                        albumsLoaded = true;
                    }
                });
            }
            $(this).find('.triangle').toggleClass('rotate');
            $albumsContainer.toggle();
        });
        $('.get-milestones').click(function () {
            var getMilestonesContainerLoaded = false;

            var $getMilestonesContainer = $('#get-milestones-container')

            if (!getMilestonesContainerLoaded) {
                $.ajax({
                    data: null,
                    url: '/ArtistPages/GetMilestones',
                    success: function (data) {
                        $getMilestonesContainer.html(data);
                        getMilestonesContainerLoaded = true;
                    }
                });
            }
            $(this).find('.triangle').toggleClass('rotate');
            $getMilestonesContainer.toggle();
        });
        $('.get-artist-report').click(function () {
            var getArtistReportContainerLoaded = false;

            var $getArtistReportContainer = $('#get-artist-report-container')

            if (!getArtistReportContainerLoaded) {
                $.ajax({
                    data: null,
                    url: '/ArtistPages/GetArtistReport',
                    success: function (data) {
                        $getArtistReportContainer.html(data);
                        getArtistReportContainerLoaded = true;
                    }
                });
            }
            $(this).find('.triangle').toggleClass('rotate');
            $getArtistReportContainer.toggle();
        });
    });
</script>

MusicLibraryTest2/Views/ArtistPages/_AddMusic.cshtml
@model MusicLibraryTest2.Models.ProfileModel

<div sub-toggle>
    <span class="get-album-form toggle-button">
        <span class="triangle"></span>
        Create Album
    </span>

    <span class="get-song-form toggle-button">
        <span class="triangle"></span>
        Create Song
    </span>

    <div class="toggle-container" id="get-album-form-container"></div>
    <div class="songForm toggle-container" id="song-form-container"></div>
</div>


<script>
    $(document).ready(function () {

        var songFormLoaded = false;
        var albumFormLoaded = false;

        $('.get-song-form').click(function () {

            var $songFormContainer = $('#song-form-container')

            if (!songFormLoaded) {
                $.ajax({
                    data: { id: @Model.Id },
                    url: '/ArtistPages/CreateSongForm',
                    success: function (data) {
                        $songFormContainer.append(data);
                        songFormLoaded = true;
                    }
                });
            }
            $(this).find('.triangle').toggleClass('rotate');
            $songFormContainer.toggle();
        });
        $('.get-album-form').click(function () {

            var $albumFormContainer = $('#get-album-form-container')

            if (!albumFormLoaded) {
                $.ajax({
                    url: '/ArtistPages/CreateAlbumForm',
                    data: null,
                    success: function (data) {
                        $albumFormContainer.append(data);
                        albumFormLoaded = true;
                    }
                });
            }
            $(this).find('.triangle').toggleClass('rotate');
            $albumFormContainer.toggle();
        });
    });
</script>

MusicLibraryTest2/Views/ArtistPages/_Albums.cshtml
@model MusicLibraryTest2.Models.AlbumModels

@foreach (var album in Model.Albums)
{
    <div class="info-box" id="info-box-@album.Id">

        <span class="album-playlist-head">Album: </span>
        <span class="album-playlist-body">@album.Title</span>
        <br />
        <br />
        <span class="album-playlist-head">Artist: </span>
        <span class="album-playlist-body">@album.ArtistName</span>
        <br />
        <br />
        <span class="album-playlist-head">Genre: </span>
        <span class="album-playlist-body">@album.Genre</span>
        <br />
        <br />
        <span class="album-playlist-head">Release Date: </span>
        <span class="album-playlist-body">@album.ReleaseDate</span>
        <br />
        <br />

        @if (album.Description != null && album.Description != "")
        {
            <span class="album-playlist-head">Description</span>
            <p class="album-playlist-body">@album.Description</p>
        }
        <br />
        <br />

        <button class="edit-album-button" data-edit-album-id="@album.Id">
            <i class="fa-solid fa-wrench unclicked-icon"></i>
        </button>

        <button class="archive-album-button" data-archive-album-id="@album.Id">
            <i class="fa-solid fa-square-xmark unclicked-icon"></i>
        </button>

        <div class="edit-container" id="edit-box-@album.Id" data-edit-album-id="@album.Id">
            @Html.Action("EditAlbumForm", "ArtistPages", album)
        </div>

        <span class="load-songs toggle-button sub-toggle " data-album-id="@album.Id">
            <span class="triangle"></span>
            Load Songs
        </span>

        <div class="songs toggle-container sub-container" id="album-@album.Id"></div>
    </div>
}

<script>
    $(document).ready(function () {

        $('.load-songs').click(function () {
            var albumId = $(this).data('album-id');
            var $albumSongsContainer = $('#album-' + albumId);


            if (true) {

                $.ajax({
                    url: '/ArtistPages/GetAlbumSongs',
                    type: 'GET',
                    data: { albumId: albumId },
                    success: function (result) {
                        $albumSongsContainer.html(result);
                    }
                });
            }

            $(this).find('.triangle').toggleClass('rotate');
            $albumSongsContainer.toggle();
        });
        $('.archive-album-button').click(function () {

            var button = $(this);
            var albumArchiveId = $(this).data('archive-album-id');
            var $infoBox = $('#info-box-' + albumArchiveId);
            $.ajax({
                url: '/ArtistPages/ArchiveAlbum',
                type: 'GET',
                data: { albumId: albumArchiveId },
                success: function (data) {

                    button.find('.unclicked-icon').removeClass('unclicked-icon');
                    setTimeout(function () {
                        button.find('.unclicked-icon').removeClass('unclicked-icon');
                    }, 1000);
                    $infoBox.toggle();
                }
            });
        });
        $('.edit-album-button').click(function () {
            var button = $(this);
            var albumEditId = $(this).data('edit-album-id');
            var $editAlbumBox = $('#edit-box-' + albumEditId);

            $editAlbumBox.toggle();
        });
    });
</script>

MusicLibraryTest2/Views/ArtistPages/_ArtistReport.cshtml
@model MusicLibraryTest2.Models.ArtistReportModels

<h2>Your Top Songs of the Month</h2>

@foreach (var report in Model.ArtistReports)
{
    <div class="artist-report">
        <span class="report-head">Song: </span><span class="report-body"> @report.SongName</span>
        <br>
        <br>
        <span class="report-head">Album: </span><span class="report-body"> @report.AlbumName</span>
        <br>
        <br>
        <span class="report-head">Monthly Views: </span><span class="report-body"> @report.Views</span>
        <br>
        <br>
        <span class="report-head">Monthly Likes: </span><span class="report-body"> @report.Likes</span>
        <br>
        <br>
        <span class="report-head">Monthly Playlist Adds: </span><span class="report-body"> @report.PlaylistAdds</span>
        <br>
        <br>
    </div>
}

@if (Model.ArtistReports.Count == 0)
{
    <div class="has-error">No Reports to Display</div>
}

MusicLibraryTest2/Views/ArtistPages/_CreateAlbumForm.cshtml
@model MusicLibraryTest2.Models.CreateAlbumModel

@{
    ViewBag.Title = "Create Album";
}
<div class="entry-box">
    @using (Html.BeginForm("CreateAlbum", "ArtistPages", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.LabelFor(model => model.Title)
        <br>
        @Html.TextBoxFor(model => model.Title)
        <br>
        @Html.LabelFor(model => model.Genre)
        <br>
        @Html.TextBoxFor(model => model.Genre)
        <br>
        @Html.LabelFor(model => model.ReleaseDateTime)
        <br>
        @Html.TextBoxFor(model => model.ReleaseDateTime, "{0:d}", new { @class = "form-control" })
        <br>
        <br>
        @Html.LabelFor(model => model.Description)
        <br>
        @Html.TextAreaFor(model => model.Description)
        <br>
        <br>

        <input id="Submit" type="submit" value="Create" />
    }
</div>

MusicLibraryTest2/Views/ArtistPages/_CreateSongForm.cshtml
@model MusicLibraryTest2.Models.CreateSongModel

@{
    ViewBag.Title = "Create Song";
}

<div class="entry-box">
    @using (Html.BeginForm("CreateSong", "ArtistPages", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.LabelFor(model => model.Title)
        <br>
        @Html.TextBoxFor(model => model.Title)
        <br>
        @Html.LabelFor(model => model.Genre)
        <br>
        @Html.TextBoxFor(model => model.Genre)
        <br>
        <br>
        @Html.LabelFor(model => model.songFile)
        <br>
        @Html.TextBoxFor(m => m.songFile, new { type = "file" })
        @Html.ValidationMessageFor(m => m.songFile)
        <br>
        <br>

        var selectList = new SelectList(Model.UserAlbumDictionary, "Value", "Key");

        <label>Add to Album</label>
        @Html.DropDownListFor(m => m.albumId, selectList, "No Album", new { @class = "form-control" })
        <input id="Submit" type="submit" value="Create" />
    }

</div>

MusicLibraryTest2/Views/ArtistPages/_EditAlbumForm.cshtml
@model MusicLibraryTest2.Models.EditAlbumModel

@{
    ViewBag.Title = "Edit Album";
}
<div class="mainBox">
    @using (Html.BeginForm("EditAlbum", "ArtistPages", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.LabelFor(model => model.Title)
        <br>
        @Html.TextBoxFor(model => model.Title)
        <br>
        @Html.LabelFor(model => model.Genre)
        <br>
        @Html.TextBoxFor(model => model.Genre)
        <br>
        <br>
        @Html.LabelFor(model => model.Description)
        <br>
        @Html.TextAreaFor(model => model.Description)
        <br>
        <br>

        @Html.HiddenFor(model => model.Id)

        <input id="Submit" type="submit" value="Submit" />
    }
</div>

MusicLibraryTest2/Views/ArtistPages/_EditSongForm.cshtml
@model MusicLibraryTest2.Models.EditSongModel

@{
    ViewBag.Title = "Edit Song";
}

<div class="mainBox">
    @using (Html.BeginForm("EditSong", "ArtistPages", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.LabelFor(model => model.Title)
        <br>
        @Html.TextBoxFor(model => model.Title)
        <br>
        @Html.LabelFor(model => model.Genre)
        <br>
        @Html.TextBoxFor(model => model.Genre)
        <br>
        <br>

        @Html.HiddenFor(model => model.Id)

        <input id="Submit" type="submit" value="Submit" />
    }

</div>